export const citiesData = [
    { name: "Agra", state: "Uttar Pradesh" },
    { name: "Ahmedabad", state: "Gujarat" },
    { name: "Ajmer", state: "Rajasthan" },
    { name: "Akola", state: "Maharashtra" },
    { name: "Alappuzha", state: "Kerala" },
    { name: "Aligarh", state: "Uttar Pradesh" },
    { name: "Allahabad", state: "Uttar Pradesh" },
    { name: "Ambernath", state: "Maharashtra" },
    { name: "Amritsar", state: "Punjab" },
    { name: "Anand", state: "Gujarat" },
    { name: "Anantapur", state: "Andhra Pradesh" },
    { name: "Arrah", state: "Bihar" },
    { name: "Asansol", state: "West Bengal" },
    { name: "Aurangabad", state: "Maharashtra" },
    { name: "Aurangabad", state: "Bihar" },
    { name: "Avadi", state: "Tamil Nadu" },
    { name: "Baharampur", state: "West Bengal" },
    { name: "Bahraich", state: "Uttar Pradesh" },
    { name: "Ballia", state: "Uttar Pradesh" },
    { name: "Bally", state: "West Bengal" },
    { name: "Baranagar", state: "West Bengal" },
    { name: "Barasat", state: "West Bengal" },
    { name: "Bardhaman", state: "West Bengal" },
    { name: "Bareilly", state: "Uttar Pradesh" },
    { name: "Barmer", state: "Rajasthan" },
    { name: "Bathinda", state: "Punjab" },
    { name: "Beawar", state: "Rajasthan" },
    { name: "Begusarai", state: "Bihar" },
    { name: "Belgaum", state: "Karnataka" },
    { name: "Bellary", state: "Karnataka" },
    { name: "Berhampur", state: "Odisha" },
    { name: "Bettiah", state: "Bihar" },
    { name: "Bhagalpur", state: "Bihar" },
    { name: "Bharatpur", state: "Rajasthan" },
    { name: "Bhatpara", state: "West Bengal" },
    { name: "Bhavnagar", state: "Gujarat" },
    { name: "Bhilai", state: "Chhattisgarh" },
    { name: "Bhilwara", state: "Rajasthan" },
    { name: "Bhimavaram", state: "Andhra Pradesh" },
    { name: "Bhind", state: "Madhya Pradesh" },
    { name: "Bhiwandi", state: "Maharashtra" },
    { name: "Bhiwani", state: "Haryana" },
    { name: "Bhopal", state: "Madhya Pradesh" },
    { name: "Bhubaneswar", state: "Odisha" },
    { name: "Bhusawal", state: "Maharashtra" },
    { name: "Bidar", state: "Karnataka" },
    { name: "Bidhan Nagar", state: "West Bengal" },
    { name: "Bihar Sharif", state: "Bihar" },
    { name: "Bijapur", state: "Karnataka" },
    { name: "Bikaner", state: "Rajasthan" },
    { name: "Bilaspur", state: "Chhattisgarh" },
    { name: "Bokaro", state: "Jharkhand" },
    { name: "Bongaigaon City", state: "Assam" },
    { name: "Brahmapur", state: "Odisha" },
    { name: "Bulandshahr", state: "Uttar Pradesh" },
    { name: "Bundi", state: "Rajasthan" },
    { name: "Burhanpur", state: "Madhya Pradesh" },
    { name: "Buxar", state: "Bihar" },
    { name: "Chandausi", state: "Uttar Pradesh" },
    { name: "Chandigarh", state: "Chandigarh" },
    { name: "Chandrapur", state: "Maharashtra" },
    { name: "Chapra", state: "Bihar" },
    { name: "Chennai", state: "Tamil Nadu" },
    { name: "Chinsurah", state: "West Bengal" },
    { name: "Chittoor", state: "Andhra Pradesh" },
    { name: "Chittorgarh", state: "Rajasthan" },
    { name: "Coimbatore", state: "Tamil Nadu" },
    { name: "Cuttack", state: "Odisha" },
    { name: "Darbhanga", state: "Bihar" },
    { name: "Datia", state: "Madhya Pradesh" },
    { name: "Davanagere", state: "Karnataka" },
    { name: "Dehradun", state: "Uttarakhand" },
    { name: "Dehri", state: "Bihar" },
    { name: "Delhi", state: "Delhi" },
    { name: "Deoghar", state: "Jharkhand" },
    { name: "Dewas", state: "Madhya Pradesh" },
    { name: "Dhanbad", state: "Jharkhand" },
    { name: "Dharmavaram", state: "Andhra Pradesh" },
    { name: "Dhule", state: "Maharashtra" },
    { name: "Dibrugarh", state: "Assam" },
    { name: "Dimapur", state: "Nagaland" },
    { name: "Dindigul", state: "Tamil Nadu" },
    { name: "Durg", state: "Chhattisgarh" },
    { name: "Durgapur", state: "West Bengal" },
    { name: "Eluru", state: "Andhra Pradesh" },
    { name: "Erode", state: "Tamil Nadu" },
    { name: "Etawah", state: "Uttar Pradesh" },
    { name: "Faizabad", state: "Uttar Pradesh" },
    { name: "Faridabad", state: "Haryana" },
    { name: "Faridabad", state: "Uttar Pradesh" },
    { name: "Farrukhabad", state: "Uttar Pradesh" },
    { name: "Fatehpur", state: "Uttar Pradesh" },
    { name: "Firozabad", state: "Uttar Pradesh" },
    { name: "Gandhidham", state: "Gujarat" },
    { name: "Gandhinagar", state: "Gujarat" },
    { name: "Gangtok", state: "Sikkim" },
    { name: "Gaya", state: "Bihar" },
    { name: "Ghaziabad", state: "Uttar Pradesh" },
    { name: "Giridih", state: "Jharkhand" },
    { name: "Godhra", state: "Gujarat" },
    { name: "Gorakhpur", state: "Uttar Pradesh" },
    { name: "Gudivada", state: "Andhra Pradesh" },
    { name: "Gulbarga", state: "Karnataka" },
    { name: "Guna", state: "Madhya Pradesh" },
    { name: "Guntakal", state: "Andhra Pradesh" },
    { name: "Guntur", state: "Andhra Pradesh" },
    { name: "Gurgaon", state: "Haryana" },
    { name: "Guwahati", state: "Assam" },
    { name: "Gwalior", state: "Madhya Pradesh" },
    { name: "Haldia", state: "West Bengal" },
    { name: "Haldwani", state: "Uttarakhand" },
    { name: "Hapur", state: "Uttar Pradesh" },
    { name: "Haridwar", state: "Uttarakhand" },
    { name: "Hazaribagh", state: "Jharkhand" },
    { name: "Hindupur", state: "Andhra Pradesh" },
    { name: "Hisar", state: "Haryana" },
    { name: "Hooghly", state: "West Bengal" },
    { name: "Hospet", state: "Karnataka" },
    { name: "Howrah", state: "West Bengal" },
    { name: "Hubballi-Dharwad", state: "Karnataka" },
    { name: "Hyderabad", state: "Telangana" },
    { name: "Ichalkaranji", state: "Maharashtra" },
    { name: "Imphal", state: "Manipur" },
    { name: "Indore", state: "Madhya Pradesh" },
    { name: "Jabalpur", state: "Madhya Pradesh" },
    { name: "Jaipur", state: "Rajasthan" },
    { name: "Jalandhar", state: "Punjab" },
    { name: "Jalgaon", state: "Maharashtra" },
    { name: "Jalna", state: "Maharashtra" },
    { name: "Jalpaiguri", state: "West Bengal" },
    { name: "Jamalpur", state: "Bihar" },
    { name: "Jammu", state: "Jammu and Kashmir" },
    { name: "Jamnagar", state: "Gujarat" },
    { name: "Jamshedpur", state: "Jharkhand" },
    { name: "Jamui", state: "Bihar" },
    { name: "Jhansi", state: "Uttar Pradesh" },
    { name: "Jharia", state: "Jharkhand" },
    { name: "Jodhpur", state: "Rajasthan" },
    { name: "Junagadh", state: "Gujarat" },
    { name: "Kadapa", state: "Andhra Pradesh" },
    { name: "Kakinada", state: "Andhra Pradesh" },
    { name: "Kalyan-Dombivali", state: "Maharashtra" },
    { name: "Kamarhati", state: "West Bengal" },
    { name: "Kanpur", state: "Uttar Pradesh" },
    { name: "Karaikudi", state: "Tamil Nadu" },
    { name: "Karawal Nagar", state: "Delhi" },
    { name: "Karimnagar", state: "Telangana" },
    { name: "Karnal", state: "Haryana" },
    { name: "Katihar", state: "Bihar" },
    { name: "Katni", state: "Madhya Pradesh" },
    { name: "Khammam", state: "Telangana" },
    { name: "Khandwa", state: "Madhya Pradesh" },
    { name: "Khanna", state: "Punjab" },
    { name: "Kharagpur", state: "West Bengal" },
    { name: "Kharar", state: "Punjab" },
    { name: "Khora", state: "Uttar Pradesh" },
    { name: "Kirari Suleman Nagar", state: "Delhi" },
    { name: "Kochi", state: "Kerala" },
    { name: "Kolhapur", state: "Maharashtra" },
    { name: "Kolkata", state: "West Bengal" },
    { name: "Kollam", state: "Kerala" },
    { name: "Korba", state: "Chhattisgarh" },
    { name: "Kota", state: "Rajasthan" },
    { name: "Kottayam", state: "Kerala" },
    { name: "Kozhikode", state: "Kerala" },
    { name: "Kulti", state: "West Bengal" },
    { name: "Kumbakonam", state: "Tamil Nadu" },
    { name: "Latur", state: "Maharashtra" },
    { name: "Loni", state: "Uttar Pradesh" },
    { name: "Lucknow", state: "Uttar Pradesh" },
    { name: "Ludhiana", state: "Punjab" },
    { name: "Machilipatnam", state: "Andhra Pradesh" },
    { name: "Madanapalle", state: "Andhra Pradesh" },
    { name: "Madhyamgram", state: "West Bengal" },
    { name: "Madurai", state: "Tamil Nadu" },
    { name: "Mahbubnagar", state: "Telangana" },
    { name: "Mahesana", state: "Gujarat" },
    { name: "Malerkotla", state: "Punjab" },
    { name: "Malegaon", state: "Maharashtra" },
    { name: "Mangalore", state: "Karnataka" },
    { name: "Mango", state: "Jharkhand" },
    { name: "Mathura", state: "Uttar Pradesh" },
    { name: "Maunath Bhanjan", state: "Uttar Pradesh" },
    { name: "Meerut", state: "Uttar Pradesh" },
    { name: "Mira-Bhayandar", state: "Maharashtra" },
    { name: "Miryalaguda", state: "Telangana" },
    { name: "Mirzapur", state: "Uttar Pradesh" },
    { name: "Moradabad", state: "Uttar Pradesh" },
    { name: "Morbi", state: "Gujarat" },
    { name: "Morena", state: "Madhya Pradesh" },
    { name: "Motihari", state: "Bihar" },
    { name: "Mumbai", state: "Maharashtra" },
    { name: "Munger", state: "Bihar" },
    { name: "Murwara", state: "Madhya Pradesh" },
    { name: "Muzaffarnagar", state: "Uttar Pradesh" },
    { name: "Muzaffarpur", state: "Bihar" },
    { name: "Mysore", state: "Karnataka" },
    { name: "Nadiad", state: "Gujarat" },
    { name: "Nagaon", state: "Assam" },
    { name: "Nagercoil", state: "Tamil Nadu" },
    { name: "Nagpur", state: "Maharashtra" },
    { name: "Naihati", state: "West Bengal" },
    { name: "Nanded", state: "Maharashtra" },
    { name: "Nandyal", state: "Andhra Pradesh" },
    { name: "Nangloi Jat", state: "Delhi" },
    { name: "Narasaraopet", state: "Andhra Pradesh" },
    { name: "Nashik", state: "Maharashtra" },
    { name: "Navi Mumbai", state: "Maharashtra" },
    { name: "Navsari", state: "Gujarat" },
    { name: "Nellore", state: "Andhra Pradesh" },
    { name: "New Delhi", state: "Delhi" },
    { name: "Nizamabad", state: "Telangana" },
    { name: "Noida", state: "Uttar Pradesh" },
    { name: "North Dumdum", state: "West Bengal" },
    { name: "Ongole", state: "Andhra Pradesh" },
    { name: "Orai", state: "Uttar Pradesh" },
    { name: "Ozhukarai", state: "Puducherry" },
    { name: "Palakkad", state: "Kerala" },
    { name: "Palanpur", state: "Gujarat" },
    { name: "Pali", state: "Rajasthan" },
    { name: "Pallavaram", state: "Tamil Nadu" },
    { name: "Panchkula", state: "Haryana" },
    { name: "Panihati", state: "West Bengal" },
    { name: "Panipat", state: "Haryana" },
    { name: "Panvel", state: "Maharashtra" },
    { name: "Parbhani", state: "Maharashtra" },
    { name: "Patan", state: "Gujarat" },
    { name: "Pathankot", state: "Punjab" },
    { name: "Patiala", state: "Punjab" },
    { name: "Patna", state: "Bihar" },
    { name: "Phagwara", state: "Punjab" },
    { name: "Phusro", state: "Jharkhand" },
    { name: "Pimpri-Chinchwad", state: "Maharashtra" },
    { name: "Pondicherry", state: "Puducherry" },
    { name: "Porbandar", state: "Gujarat" },
    { name: "Port Blair", state: "Andaman and Nicobar Islands" },
    { name: "Proddatur", state: "Andhra Pradesh" },
    { name: "Pudukkottai", state: "Tamil Nadu" },
    { name: "Pune", state: "Maharashtra" },
    { name: "Puri", state: "Odisha" },
    { name: "Purnia", state: "Bihar" },
    { name: "Raebareli", state: "Uttar Pradesh" },
    { name: "Raichur", state: "Karnataka" },
    { name: "Raiganj", state: "West Bengal" },
    { name: "Raipur", state: "Chhattisgarh" },
    { name: "Rajahmundry", state: "Andhra Pradesh" },
    { name: "Rajkot", state: "Gujarat" },
    { name: "Rajpur Sonarpur", state: "West Bengal" },
    { name: "Ramagundam", state: "Telangana" },
    { name: "Rampur", state: "Uttar Pradesh" },
    { name: "Ranchi", state: "Jharkhand" },
    { name: "Ratlam", state: "Madhya Pradesh" },
    { name: "Raurkela", state: "Odisha" },
    { name: "Rewa", state: "Madhya Pradesh" },
    { name: "Rohtak", state: "Haryana" },
    { name: "Rourkela", state: "Odisha" },
    { name: "Sagar", state: "Madhya Pradesh" },
    { name: "Saharanpur", state: "Uttar Pradesh" },
    { name: "Saharsa", state: "Bihar" },
    { name: "Salem", state: "Tamil Nadu" },
    { name: "Sambalpur", state: "Odisha" },
    { name: "Sambhal", state: "Uttar Pradesh" },
    { name: "Sangli-Miraj & Kupwad", state: "Maharashtra" },
    { name: "Satara", state: "Maharashtra" },
    { name: "Satna", state: "Madhya Pradesh" },
    { name: "Secunderabad", state: "Telangana" },
    { name: "Serampore", state: "West Bengal" },
    { name: "Shahjahanpur", state: "Uttar Pradesh" },
    { name: "Shimla", state: "Himachal Pradesh" },
    { name: "Shimoga", state: "Karnataka" },
    { name: "Shivpuri", state: "Madhya Pradesh" },
    { name: "Sikar", state: "Rajasthan" },
    { name: "Silchar", state: "Assam" },
    { name: "Siliguri", state: "West Bengal" },
    { name: "Singrauli", state: "Madhya Pradesh" },
    { name: "Sirsa", state: "Haryana" },
    { name: "Siwan", state: "Bihar" },
    { name: "Solapur", state: "Maharashtra" },
    { name: "Sonipat", state: "Haryana" },
    { name: "South Dumdum", state: "West Bengal" },
    { name: "Sri Ganganagar", state: "Rajasthan" },
    { name: "Srinagar", state: "Jammu and Kashmir" },
    { name: "Sultan Pur Majra", state: "Delhi" },
    { name: "Surat", state: "Gujarat" },
    { name: "Surendranagar Dudhrej", state: "Gujarat" },
    { name: "Suryapet", state: "Telangana" },
    { name: "Tadepalligudem", state: "Andhra Pradesh" },
    { name: "Tadipatri", state: "Andhra Pradesh" },
    { name: "Tenali", state: "Andhra Pradesh" },
    { name: "Tezpur", state: "Assam" },
    { name: "Thane", state: "Maharashtra" },
    { name: "Thiruvananthapuram", state: "Kerala" },
    { name: "Thrissur", state: "Kerala" },
    { name: "Tiruchirappalli", state: "Tamil Nadu" },
    { name: "Tirunelveli", state: "Tamil Nadu" },
    { name: "Tirupati", state: "Andhra Pradesh" },
    { name: "Tiruppur", state: "Tamil Nadu" },
    { name: "Tiruvottiyur", state: "Tamil Nadu" },
    { name: "Tumkur", state: "Karnataka" },
    { name: "Udaipur", state: "Rajasthan" },
    { name: "Udgir", state: "Maharashtra" },
    { name: "Udupi", state: "Karnataka" },
    { name: "Ujjain", state: "Madhya Pradesh" },
    { name: "Ulhasnagar", state: "Maharashtra" },
    { name: "Unnao", state: "Uttar Pradesh" },
    { name: "Vadodara", state: "Gujarat" },
    { name: "Valsad", state: "Gujarat" },
    { name: "Vapi", state: "Gujarat" },
    { name: "Varanasi", state: "Uttar Pradesh" },
    { name: "Vasai-Virar", state: "Maharashtra" },
    { name: "Vellore", state: "Tamil Nadu" },
    { name: "Vijayanagaram", state: "Andhra Pradesh" },
    { name: "Vijayawada", state: "Andhra Pradesh" },
    { name: "Visakhapatnam", state: "Andhra Pradesh" },
    { name: "Vizianagaram", state: "Andhra Pradesh" },
    { name: "Warangal", state: "Telangana" },
    { name: "Wardha", state: "Maharashtra" },
    { name: "Yamunanagar", state: "Haryana" },
    { name: "Yavatmal", state: "Maharashtra" },
    { name: "Yemmiganur", state: "Andhra Pradesh" },
  ];
  